services:
  wonderk.webpanel:
    image: ${DOCKER_REGISTRY-}wonderkwebpanel
    build:
      context: .
      dockerfile: WonderK.WebPanel/Dockerfile

  wonderk.rulechecker:
    image: ${DOCKER_REGISTRY-}rulechecker
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: WonderK.RuleChecker/Dockerfile

  wonderk.departmentheavy:
    image: ${DOCKER_REGISTRY-}departmentheavy
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: WonderK.department.Heavy/Dockerfile

  wonderk.departmentinsurance:
    image: ${DOCKER_REGISTRY-}departmentinsurance
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: WonderK.department.Insurance/Dockerfile

  wonderk.departmentmail:
    image: ${DOCKER_REGISTRY-}departmentmail
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: WonderK.department.Mail/Dockerfile

  wonderk.departmentregular:
    image: ${DOCKER_REGISTRY-}departmentregular
    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: WonderK.department.Regular/Dockerfile

  redis:
     image: redis
